### ISSUE TITLE
In line with the ViUR Core 3.5 release we should also provide a Github release in Base.

### ISSUE THREAD

**Issue by theVAX** [viur-framework/viur-base#106]
There hasn't been a Github release since 2019.

**Comment by phorward** [comment]
Ok we decided to make tags but no releases.

**Comment by sveneberth** [comment]
Hello all,

I have now created two tags after merging the dependency PR #110. 
- [`v3.4.4`](https://github.com/viur-framework/viur-base/releases/tag/v3.4.4)
- [`v3.5.1`](https://github.com/viur-framework/viur-base/releases/tag/v3.5.1)

As @phorward had already written, we have now decided that there should be no more releases. 

Thus I close the ticket.
